{% set version = '3.98-1.19' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/XML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/XML/XML_{{ version }}.tar.gz
  sha256: 81b1c4a2df24c5747fa8b8ec2d76b4e9c3649b56ca94f6c93fbd106c8a72beab

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - libxml2 2.9.*

  run:
    - r-base
    - libxml2 2.9.*
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('XML')"           # [not win]
    - "\"%R%\" -e \"library('XML')\""  # [win]

about:
  home: http://www.omegahat.net/RSXML
  license: BSD_2_clause
  summary: Many approaches for both reading and creating XML (and HTML) documents (including
    DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath'
    "interpreter".
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1

# Package: XML
# Version: 3.98-1.19
# Author: Duncan Temple Lang and the CRAN Team (including Tomas Kalibera)
# Maintainer: ORPHANED
# Title: Tools for Parsing and Generating XML Within R and S-Plus
# Depends: R (>= 2.13.0), methods, utils
# Suggests: bitops, RCurl
# SystemRequirements: libxml2 (>= 2.6.3)
# Description: Many approaches for both reading and creating XML (and HTML) documents (including DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath' "interpreter".
# URL: http://www.omegahat.net/RSXML
# License: BSD_2_clause + file LICENSE
# Collate: AAA.R DTD.R DTDClasses.R DTDRef.R SAXMethods.S XMLClasses.R applyDOM.R assignChild.R catalog.R createNode.R dynSupports.R error.R flatTree.R nodeAccessors.R parseDTD.R schema.S summary.R tangle.R toString.S tree.R version.R xmlErrorEnums.R xmlEventHandler.R xmlEventParse.R xmlHandler.R xmlInternalSource.R xmlOutputDOM.R xmlNodes.R xmlOutputBuffer.R xmlTree.R xmlTreeParse.R htmlParse.R hashTree.R zzz.R supports.R parser.R libxmlFeatures.R xmlString.R saveXML.R namespaces.R readHTMLTable.R reflection.R xmlToDataFrame.R bitList.R compare.R encoding.R fixNS.R xmlRoot.R serialize.R xmlMemoryMgmt.R keyValueDB.R solrDocs.R XMLRErrorInfo.R xincludes.R namespaceHandlers.R tangle1.R htmlLinks.R htmlLists.R getDependencies.R getRelativeURL.R xmlIncludes.R simplifyPath.R
# NeedsCompilation: yes
# Packaged: 2019-03-06 17:04:34 UTC; ripley
# X-CRAN-Comment: Orphaned on 2017-06-19: all updates have been by the CRAN team for some years.
# Repository: CRAN
# Date/Publication: 2019-03-06 20:40:34 UTC
